version: '3'

services:
  summarize_docs:
    build: .
    container_name: summarize_docs
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
